"""Project workspace management.

Manages project-level workspaces within the global workspace.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from myagent.memory.manager import MemoryManager
from myagent.workspace.manager import get_projects_dir


class ProjectManager:
    """Manages project workspaces."""

    def __init__(self, workspace_dir: Path | None = None) -> None:
        self.projects_dir = get_projects_dir(workspace_dir)

    def create_project(self, name: str, description: str = "") -> Path:
        """Create a new project workspace.

        Args:
            name: Project name
            description: Optional project description

        Returns:
            Path to the project directory
        """
        project_dir = self.projects_dir / name

        dirs = [
            project_dir,
            project_dir / ".myagent",
            project_dir / ".myagent" / "memory",
            project_dir / ".myagent" / "agents",
            project_dir / ".myagent" / "tasks",
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)

        # Write project metadata
        meta_path = project_dir / ".myagent" / "project.md"
        meta_path.write_text(
            f"""# {name}

{description}

## Created
Auto-generated by MyAgent

## Status
Active
""",
            encoding="utf-8",
        )

        return project_dir

    def list_projects(self) -> list[dict[str, Any]]:
        """List all projects.

        Returns:
            List of project info dicts
        """
        if not self.projects_dir.exists():
            return []

        projects = []
        for path in sorted(self.projects_dir.iterdir()):
            if not path.is_dir():
                continue

            meta_path = path / ".myagent" / "project.md"
            description = ""
            if meta_path.exists():
                content = meta_path.read_text(encoding="utf-8")
                lines = content.split('\n')
                if len(lines) > 2:
                    description = lines[2].strip()

            projects.append({
                "name": path.name,
                "path": str(path),
                "description": description,
            })

        return projects

    def get_project(self, name: str) -> Path | None:
        """Get a project directory.

        Args:
            name: Project name

        Returns:
            Project directory path or None if not found
        """
        project_dir = self.projects_dir / name
        if project_dir.exists():
            return project_dir
        return None

    def get_project_memory_manager(self, name: str) -> MemoryManager | None:
        """Get the memory manager for a project.

        Args:
            name: Project name

        Returns:
            MemoryManager for the project or None
        """
        project_dir = self.get_project(name)
        if not project_dir:
            return None

        memory_dir = project_dir / ".myagent" / "memory"
        return MemoryManager(memory_dir)

    def delete_project(self, name: str) -> bool:
        """Delete a project.

        Args:
            name: Project name

        Returns:
            True if deleted, False if not found
        """
        import shutil

        project_dir = self.projects_dir / name
        if not project_dir.exists():
            return False

        shutil.rmtree(project_dir)
        return True
